version: '3'
services:
  mysqlsamuel:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: dbmysql
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bancodados
    networks:
      - uaa-net
      
  admineruaa:
    image: adminer
    restart: always
    ports:
      - 9091:8080
    networks:
      - uaa-net

networks:
  uaa-net:
    driver: bridge
